version: "3.9"

services:
  web:
    build: .
    container_name: mediaamp_web
    command: gunicorn --bind 0.0.0.0:5000 run:app
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: mediaamp_db
    environment:
      POSTGRES_USER: hardik
      POSTGRES_PASSWORD: hardik123
      POSTGRES_DB: mediaamp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mediaamp_redis
    ports:
      - "6380:6379"

  celery:
    build: .
    container_name: mediaamp_celery
    command: celery -A app.celery_worker.celery worker --loglevel=info
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
