"""Add TaskManager and TaskLogger models

Revision ID: 914098718c91
Revises: 8890ddec1916
Create Date: 2025-04-04 17:33:22.505051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914098718c91'
down_revision = '8890ddec1916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_manager_title'), ['title'], unique=False)

    op.create_table('task_logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status_snapshot', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_logger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_logger_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_logger_task_id'))

    op.drop_table('task_logger')
    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_manager_title'))

    op.drop_table('task_manager')
    # ### end Alembic commands ###
