"""Add missing fields to TaskManager

Revision ID: c8dfa576f355
Revises: 914098718c91
Create Date: 2025-04-05 09:25:12.754939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dfa576f355'
down_revision = '914098718c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('assigned_user', sa.String(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_index('ix_task_manager_title')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_index('ix_task_manager_title', ['title'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('assigned_user')
        batch_op.drop_column('priority')
        batch_op.drop_column('task_name')

    # ### end Alembic commands ###
