"""Updated User model with password hashing

Revision ID: d339c6d40638
Revises: 2eb6ed7b0491
Create Date: 2025-04-03 08:06:26.597704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd339c6d40638'
down_revision = '2eb6ed7b0491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password', type_=sa.String(255), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # Revert password column change if needed
    op.alter_column('user', 'password', type_=sa.String(80), nullable=False)

